name: public_apis_desktop_client
version: 1.0.1+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  lint: ^1.10.0
  http: ^0.13.5
  auto_size_text: ^3.0.0
  google_fonts: ^3.0.1
  animations: ^2.0.4
  url_launcher: ^6.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.3
  build_runner: ^2.2.0
  delayed_display: ^2.0.0
  flutter_markdown: ^0.6.10+5
  share_plus: ^4.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/categoriesImages/
