name: public_apis_desktop_client
version: 1.1.0+3
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  lint: ^1.10.0
  http: ^0.13.5
  auto_size_text: ^3.0.0
  google_fonts: ^3.0.1
  animations: ^2.0.4
  url_launcher: ^6.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.3
  build_runner: ^2.2.0
  delayed_display: ^2.0.0
  flutter_markdown: ^0.6.10+5
  share_plus: ^4.1.0
  firebase_core: ^1.22.0
  firebase_analytics: ^9.3.5
  firebase_crashlytics: ^2.8.10
  flutter_launcher_icons: ^0.10.0
  in_app_review: ^2.0.4

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  image_path: "assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/categoriesImages/
