name: public_apis_desktop_client
version: 1.3.1+5
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  animations: ^2.0.4
  auto_size_text: ^3.0.0
  build_runner: ^2.2.0
  cupertino_icons: ^1.0.2
  delayed_display: ^2.0.0
  device_preview: ^1.1.0
  firebase_analytics: ^9.3.5
  firebase_core: ^1.22.0
  firebase_crashlytics: ^2.8.10
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  flutter_markdown: ^0.6.10+5
  get: 4.6.5
  google_fonts: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.3
  http: ^0.13.5
  in_app_review: ^2.0.4
  lint: ^1.10.0
  share_plus: ^4.1.0
  url_launcher: ^6.1.5

dev_dependencies:
  change_app_package_name: ^1.1.0
  dart_code_metrics: ^4.19.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  image_path: "assets/logo_play_store_rounded.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/categoriesImages/
    - assets/md_content/
